import './globals.css'
import { Inter } from 'next/font/google'
import BaseWithDrawer from "@/components/base_theme/base";
import CssBaseline from "@mui/material/CssBaseline";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CssBaseline/>
      <body className={inter.className}>
        <BaseWithDrawer admin={true} main_content={children} />
      </body>
    </html>
  )
}