import './globals.css'
import { Inter } from 'next/font/google'
import TemporaryDrawer from "@/components/base_theme/sidebar_temporary";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//             {/*<PrimarySearchAppBar/>*/}
//             <ClippedDrawer />
//             {children}
//       </body>
//     </html>
//   )
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <TemporaryDrawer />
            {children}
      </body>
    </html>
  )
}